---
driver:
  name: vagrant
  require_chef_omnibus: 12.4.1

driver_config:
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
- name: centos-6
  driver_config:
    box: chef/centos-6.6
  run_list:
  - recipe[yum]
- name: centos-7
  driver_config:
    box: chef/centos-7.0
  run_list:
  - recipe[yum]
- name: ubuntu-12.04
  driver_config:
    box: chef/ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  driver_config:
    box: chef/ubuntu-14.04
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[test-helper]
  - recipe[postgresql::ruby]
